---
title: "Codebook"
author: "M Tato"
date: "2016_04_03"
output:
  html_document:
    keep_md: yes
    theme: flatly
---

## Project Description
####Johns Hopkins - Getting and Cleaning Data, Course Project


##Collection of the raw data
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip


##Notes on the original (raw) data 
Data collected from the accelerometers from the Samsung Galaxy S smartphone.
Jorge L. Reyes-Ortiz, Davide Anguita, Alessandro Ghio, Luca Oneto.
Smartlab - Non Linear Complex Systems Laboratory
DITEN - University


##Tidy data file
* "tidy_groupedData.txt"


##Guide to create the tidy data file
* Code cleaning file: "run_analysis.R"


## Brief cleaning overview:
1. -- Download raw data and related files
1  -- Import results data - x_test/train.txt ---------
   -- Import subject data - subject_test/train.txt ---------
   -- Import Activity data - y_test/train.txt ---------
2. -- Select out only Mean and SD vars ---------
3. -- Merge test and train datasets ---------
4. -- Create column fo Activity Descriptions and set ---------
5. -- Revise variable names ---------
6. --Create tidy dataset grouped by Subject and Activity ---------
7. -- Write file: "tidy_groupedData.txt" ---------------------------


##Variables Information

The variables selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. 
These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. They were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 


##Variables Description 

Dataset dimensions: 180 obs. of 69 variables

Variables present in the dataset:
 $ Subject                       : int  2 2 2 2 2 2 4 4 4 4 ... 
 
 $ Activity                      : int  5 4 6 1 3 2 5 4 6 1 ...
 
 $ ActivityDescription           : chr  "STANDING" "SITTING" "LAYING" "WALKING" ...
 
 $ timedBodyAccMeanX             : num  0.278 0.277 0.281 0.276 0.278 ...
 
 $ timedBodyAccMeanY             : num  -0.0184 -0.0157 -0.0182 -0.0186 -0.0227 ...
 
 $ timedBodyAccMeanZ             : num  -0.106 -0.109 -0.107 -0.106 -0.117 ...
 
 $ timedBodyAccStndDevX          : num  -0.9873 -0.9868 -0.9741 -0.4236 0.0464 ...
 
 $ timedBodyAccStndDevY          : num  -0.9573 -0.9507 -0.9803 -0.0781 0.2629 ...
 
 $ timedBodyAccStndDevZ          : num  -0.95 -0.96 -0.984 -0.425 -0.103 ...
 
 $ timedGravityAccMeanX          : num  0.897 0.94 -0.51 0.913 0.862 ...
 
 $ timedGravityAccMeanY          : num  -0.37 -0.106 0.753 -0.347 -0.326 ...
 
 $ timedGravityAccMeanZ          : num  0.1297 0.1987 0.6468 0.0847 -0.0439 ...
 
 $ timedGravityAccStndDevX       : num  -0.987 -0.98 -0.959 -0.973 -0.94 ...
 
 $ timedGravityAccStndDevY       : num  -0.974 -0.957 -0.988 -0.972 -0.94 ...
 
 $ timedGravityAccStndDevZ       : num  -0.946 -0.954 -0.984 -0.972 -0.931 ...
 
 $ timedBodyAccJerkMeanX         : num  0.0748 0.0723 0.0826 0.0618 0.11 ...
 
 $ timedBodyAccJerkMeanY         : num  0.01033 0.0117 0.01225 0.01825 -0.00328 ...
 
 $ timedBodyAccJerkMeanZ         : num  -0.00837 0.00761 -0.0018 0.0079 -0.02094 ...
 
 $ timedBodyAccJerkStndDevX      : num  -0.981 -0.988 -0.986 -0.278 0.147 ...
 
 $ timedBodyAccJerkStndDevY      : num  -0.9711 -0.978 -0.9832 -0.0166 0.1268 ...
 
 $ timedBodyAccJerkStndDevZ      : num  -0.983 -0.988 -0.988 -0.586 -0.34 ...
 
 $ timedBodyGyroMeanX            : num  -0.0239 -0.0455 -0.0185 -0.053 -0.1159 ...
 
 $ timedBodyGyroMeanY            : num  -0.08204 -0.05993 -0.1118 -0.04824 -0.00482 ...
 
 $ timedBodyGyroMeanZ            : num  0.0878 0.0412 0.1449 0.0828 0.0972 ...
 
 $ timedBodyGyroStndDevX         : num  -0.973 -0.986 -0.988 -0.562 -0.321 ...
 
 $ timedBodyGyroStndDevY         : num  -0.971 -0.979 -0.982 -0.538 -0.416 ...
 
 $ timedBodyGyroStndDevZ         : num  -0.965 -0.96 -0.96 -0.481 -0.279 ...
 
 $ timedBodyGyroJerkMeanX        : num  -0.1056 -0.0936 -0.102 -0.0819 -0.0581 ...
 
 $ timedBodyGyroJerkMeanY        : num  -0.0422 -0.0416 -0.0359 -0.0538 -0.0421 ...
 
 $ timedBodyGyroJerkMeanZ        : num  -0.0547 -0.0436 -0.0702 -0.0515 -0.071 ...
 
 $ timedBodyGyroJerkStndDevX     : num  -0.979 -0.99 -0.993 -0.39 -0.244 ...
 
 $ timedBodyGyroJerkStndDevY     : num  -0.983 -0.991 -0.99 -0.634 -0.469 ...
 
 $ timedBodyGyroJerkStndDevZ     : num  -0.974 -0.986 -0.988 -0.435 -0.218 ...
 
 $ timedBodyAccMagMean           : num  -0.966 -0.968 -0.977 -0.29 0.09 ...
 
 $ timedBodyAccMagStndDev        : num  -0.958 -0.953 -0.973 -0.423 0.216 ...
 
 $ timedGravityAccMagMean        : num  -0.966 -0.968 -0.977 -0.29 0.09 ...
 
 $ timedGravityAccMagStndDev     : num  -0.958 -0.953 -0.973 -0.423 0.216 ...
 
 $ timedBodyAccJerkMagMean       : num  -0.98049 -0.98677 -0.98774 -0.28142 0.00566 ...
 
 $ timedBodyAccJerkMagStndDev    : num  -0.977 -0.984 -0.986 -0.164 0.23 ...
 
 $ timedBodyGyroMagMean          : num  -0.963 -0.946 -0.95 -0.447 -0.162 ...
 
 $ timedBodyGyroMagStndDev       : num  -0.954 -0.961 -0.961 -0.553 -0.275 ...
 
 $ timedBodyGyroJerkMagMean      : num  -0.984 -0.991 -0.992 -0.548 -0.411 ...
 
 $ timedBodyGyroJerkMagStndDev   : num  -0.977 -0.99 -0.99 -0.558 -0.343 ...
 
 $ freqBodyAccMeanX              : num  -0.984 -0.986 -0.977 -0.346 0.113 ...
 
 $ freqBodyAccMeanY              : num  -0.9599 -0.9573 -0.9798 -0.0219 0.2783 ...
 
 $ freqBodyAccMeanZ              : num  -0.962 -0.97 -0.984 -0.454 -0.131 ...
 
 $ freqBodyAccStndDevX           : num  -0.9891 -0.9874 -0.9732 -0.4577 0.0161 ...
 
 $ freqBodyAccStndDevY           : num  -0.958 -0.95 -0.981 -0.169 0.172 ...
 
 $ freqBodyAccStndDevZ           : num  -0.946 -0.957 -0.985 -0.455 -0.162 ...
 
 $ freqBodyAccJerkMeanX          : num  -0.981 -0.988 -0.986 -0.305 0.138 ...
 
 $ freqBodyAccJerkMeanY          : num  -0.9709 -0.9771 -0.9828 -0.0788 0.0962 ...
 
 $ freqBodyAccJerkMeanZ          : num  -0.98 -0.985 -0.986 -0.555 -0.271 ...
 
 $ freqBodyAccJerkStndDevX       : num  -0.983 -0.989 -0.987 -0.314 0.05 ...
 
 $ freqBodyAccJerkStndDevY       : num  -0.9735 -0.9808 -0.985 -0.0153 0.0808 ...
 
 $ freqBodyAccJerkStndDevZ       : num  -0.985 -0.989 -0.989 -0.616 -0.408 ...
 
 $ freqBodyGyroMeanX             : num  -0.967 -0.983 -0.986 -0.43 -0.146 ...
 
 $ freqBodyGyroMeanY             : num  -0.973 -0.982 -0.983 -0.555 -0.362 ...
 
 $ freqBodyGyroMeanZ             : num  -0.9606 -0.9598 -0.9627 -0.3967 -0.0875 ...
 
 $ freqBodyGyroStndDevX          : num  -0.975 -0.987 -0.989 -0.604 -0.379 ...
 
 $ freqBodyGyroStndDevY          : num  -0.971 -0.977 -0.982 -0.533 -0.459 ...
 
 $ freqBodyGyroStndDevZ          : num  -0.97 -0.964 -0.963 -0.56 -0.423 ...
 
 $ freqBodyAccMagMean            : num  -0.964 -0.961 -0.975 -0.324 0.293 ...
 
 $ freqBodyAccMagStndDev         : num  -0.9605 -0.9556 -0.9751 -0.5771 -0.0215 ...
 
 $ freqBodyBodyAccJerkMagMean    : num  -0.977 -0.984 -0.985 -0.169 0.222 ...
 
 $ freqBodyBodyAccJerkMagStndDev : num  -0.975 -0.984 -0.985 -0.164 0.227 ...
 
 $ freqBodyBodyGyroMagMean       : num  -0.962 -0.972 -0.972 -0.531 -0.321 ...
 
 $ freqBodyBodyGyroMagStndDev    : num  -0.957 -0.961 -0.961 -0.652 -0.373 ...
 
 $ freqBodyBodyGyroJerkMagMean   : num  -0.978 -0.99 -0.99 -0.583 -0.38 ...
 
 $ freqBodyBodyGyroJerkMagStndDev: num  -0.978 -0.99 -0.989 -0.558 -0.344 ...
 
 